all:
  hosts:
    pikube-master01:
      ansible_host: 192.168.178.10
    pikube-worker01:
      ansible_host: 192.168.178.11
  vars: 
    ansible_ssh_private_key_file: .ssh/kubernetes_management
  children:
    kube_masters:
      hosts:
        pikube-master01:
          ansible_host: 192.168.178.10
    kube_workers:
      hosts:
        pikube-worker01:
          ansible_host: 192.168.178.11
    raspberry_pis:
      hosts: 
        pikube-master01:
          ansible_host: 192.168.178.10
        pikube-worker01:
          ansible_host: 192.168.178.11