---

- name: init kubernetes cluster
  shell: 
    cmd: kubeadm init --pod-network-cidr {{ kubernetes.pod_cidr }}
    creates: /etc/kubernetes/kubelet.conf
  become: true

- name: make sure  kube config directories are present for users
  block:
    - name: create .kube directory for user 
      file:
        path: "/home/{{ item.name }}/.kube"
        state: directory
        owner: "{{ item.name }}"
        group: "{{ item.name }}"
      become: true
      loop: "{{ host_os.users }}"

- name: make sure the kubectl config is present in the kube onfig directory for users
  copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: "/home/{{ item.name }}/.kube/config"
    owner: "{{ item.name }}"
    group: "{{ item.name }}"
    mode: 0600
  become: true
  loop: "{{ host_os.users }}"
